version: "3.8"
services:
    web:
      build:
        context: .
        args:
          BUILD_PROFILE: psql_env
      ports:
        - "8080:8080"
      depends_on:
        db:
          condition: service_healthy
      environment:
        - SPRING_PROFILES_ACTIVE=psql_env
        - JDBC_POSTGRESQL_URL=jdbc:postgresql://db:5432/student
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres

    db:
      image: "postgres:15"
      volumes:
          - ./psql-data:/var/lib/postgresql/data
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=student
      healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U postgres" ]
        start_period: 8s
        interval: 1s
        timeout: 2s
        retries: 3
      ports:
          - "5432:5432"