version: "3.8"
services:
    web:
      build: .
      ports:
        - "8080:8080"
      depends_on:
        - db
#      environment:
#          - JDBC_POSTGRES_URL=jdbc:postgresql://db:5432/student
#          - POSTGRES_USERNAME=postgres
#          - POSTGRES_PASSWORD=postgres
    db:
      image: "postgres:15"
      volumes:
          - ./psql-data:/var/lib/postgresql/data
      ports:
          - "5432:5432"